repos:
  - repo: local
    hooks:
      - id: add-spdx-headers
        name: Add SPDX License Headers
        entry: python scripts/spdx_header_hook.py
        language: system
        types: [python, javascript]
        files: '^(capture|search|frontend)/.*\.(py|js)$'
        pass_filenames: true
        stages: [commit]